server:
  port: 3333

spring:
  config:
    import: configserver:http://localhost:1111
  application:
    name: eainde-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: EAINDE-CUSTOMER-SERVICE
        uri: localhost:8445
        predicates:
        - Path=/customer
      - id: EAINDE-ORDER-SERVICE
        uri: localhost:8444
        predicates:
        - Path=/order
      - id: EAINDE-USER-SERVICE
        uri: localhost:8443
        predicates:
        - Path=/user
